# Generated by Django 5.2.2 on 2025-06-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
    ]
