# Generated by Django 5.2.2 on 2025-06-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0002_veiculo_destaque'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição detalhada'),
        ),
    ]
